version: '3.4'

services:
  practice_postgresql:
    image: postgres:14.1
    
  practice_redis:
    image: redis

  practice.api:
    image: ${DOCKER_REGISTRY-}practiceapi
    build:
      context: .
      dockerfile: Systems/Api/Practice.Api/Dockerfile
