version: '3.4'

services:
  practice_postgresql:
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Passw0rd
    ports:
      - "5432:5432"
    networks:
      - shared_practice
    volumes:      
      - ~/.docker-conf/postgresql/data/:/var/lib/postgresql/data
  practice_redis:
    ports:
    - '6379:6379'
    networks:
    - shared_practice
    volumes:      
    - ~/.docker-conf/redis/data/:/data

  practice.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
    env_file:
    - env.api

networks:
  shared_practice:
    name: practice
    driver: bridge